POST http://localhost:8081/auth/login
Accept: application/json
Content-Type: application/json

{
  "login": "login",
  "password": "password"
}
###

GET http://localhost:8081/auth/logout
Accept: application/json
Content-Type: application/json
Cookie: name=value

###

POST http://localhost:8081/auth/authorize
Accept: application/json
Content-Type: application/json
Cookie: cookie=value
###
